# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build flutter-pi

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted

    container:
      image: seyriz/flutter-pi-sdk:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run build for rpi3
        run: |
          flutter pub get
          flutterpi_tool build --release --cpu=pi3
          version=${{ github.ref_name }}
          zip -r fl_tidal101_${version}_pi3.zip ./build/flutter_assets
          rm -rf ./build/flutter_assets
        
      - name: Run build for rpi4
        run: |
          flutter pub get
          flutterpi_tool build --release --cpu=pi4
          version=${{ github.ref_name }}
          zip -r fl_tidal101_${version}_pi4.zip ./build/flutter_assets
          rm -rf ./build/flutter_assets
          
      - name: Upload zip files to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            fl_tidal101_${{ github.ref_name }}_pi3.zip
            fl_tidal101_${{ github.ref_name }}_pi4.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
